using System.Collections.Generic;

namespace NonTvmTickets
{
    static class TicketRefData
    {
        private static Dictionary<string, string> codeToName = new Dictionary<string, string>
        {
            {"0AA", "Smart Child Flat Fare Single"},
            {"0AB", "Smart Child Flat Fare Return"},
            {"0AC", "Smart Anytime Day Return (1st Class)"},
            {"0AD", "Smart Anytime Day Single (1st Class)"},
            {"0AE", "Smart Anytime Day Return"},
            {"0AF", "Smart Anytime Single"},
            {"0AG", "Smart Flexi Anytime Day Return"},
            {"0AH", "Smart Flexi Anytime Day Return (1st Class)"},
            {"0AJ", "Smart Off-Peak Day Return (1st Class)"},
            {"0AK", "Smart Off-Peak Day Return"},
            {"0AL", "Smart Off-Peak Day Single"},
            {"0AM", "Smart Flexi Season Ticket"},
            {"0AN", "Smart Flexi Season Ticket (1st Class)"},
            {"0AQ", "Smart 7 Day Season Ticket"},
            {"0AR", "Smart 7 Day Season Ticket (1st Class)"},
            {"0AS", "Smart Period Season Ticket"},
            {"0AT", "Smart Period Season Ticket (1st Class)"},
            {"0AU", "Smart Flexi Period Season Ticket"},
            {"0AV", "Smart Flexi Period Season Ticket (1st Class)"},
            {"0AW", "Smart Advance Single"},
            {"0AX", "Smart Advance Single"},
            {"0AY", "Smart Advance Single"},
            {"0AZ", "Smart Advance Single (1st Class)"},
            {"0BA", "Smart Annual NTrain Season Ticket"},
            {"0BB", "Smart 6 Months NTrain Season Ticket"},
            {"0BC", "Smart 3 Months NTrain Season Ticket"},
            {"0BD", "Smart 1 Month NTrain Season Ticket"},
            {"0BE", "Smart Direct Debit Monthly NTrain Season Ticket"},
            {"0BF", "Smart 28 Days NTrain Season Ticket"},
            {"0BG", "Smart 7 Day Ntrain Season Ticket"},
            {"0BL", "Smart Off-Peak Return"},
            {"0BM", "Smart Off-Peak Return (1st Class)"},
            {"0BN", "Smart Super Off-Peak Day Single"},
            {"0BO", "Smart Super Off-Peak Day Return"},
            {"0BP", "Smart Super Off-Peak Day Single"},
            {"0BQ", "Smart Super Off-Peak Day Return"},
            {"0BR", "Smart PlusBus Day Pass"},
            {"0BS", "Smart PlusBus 7 Day Pass"},
            {"0BT", "Smart PlusBus Monthly Pass"},
            {"0BU", "Smart PlusBus 3 Months Pass"},
            {"0BV", "Smart PlusBus Annual Pass"},
            {"0BW", "Smart Super Off-Peak Day Return"},
            {"0BX", "Smart Super Off-Peak Day Travelcard"},
            {"0BY", "Smart Super Off-Peak Single"},
            {"0BZ", "Smart Child Flat Fare Travelcard"},
            {"0CA", "Smart Anytime Day Travelcard"},
            {"0CB", "Smart Anytime Day Travelcard (1st Class)"},
            {"0CC", "Smart Off-Peak Day Travelcard"},
            {"0CD", "Smart Off-Peak Day Travelcard (1st Class)"},
            {"0CE", "Smart Super Off-Peak Day Travelcard"},
            {"0CF", "Smart Super Off-Peak Day Travelcard"},
            {"0CG", "Smart Family Day Travelcard"},
            {"0CH", "Smart 7 Day Travelcard Season Ticket"},
            {"0CI", "Smart 7 Day Travelcard Season Ticket (1st Class)"},
            {"0CJ", "Smart Period Travelcard Season Ticket"},
            {"0CK", "Smart Period Travelcard Season Ticket (1st Class)"},
            {"0CL", "Smart DaySave"},
            {"0CM", "Smart Southern Daysave Group Off-Peak "},
            {"0CN", "Smart Southern Daysave Peak"},
            {"0CO", "Smart DaySave Weekly"},
            {"0CP", "Smart Bus Day Single"},
            {"0CQ", "Smart Bus Day Return"},
            {"0CR", "Smart Bus Multi"},
            {"0E1", "Smart Off-Peak Day Return (1st Class)"},
            {"0FR", "Smart Anytime Return (1st Class)"},
            {"0FS", "Smart Anytime Single (1st Class)"},
            {"0GR", "Smart Anytime Return (1st Class)"},
            {"0GS", "Smart Anytime Single (1st Class)"},
            {"0HR", "Smart Anytime Return"},
            {"0HS", "Smart Anytime Single"},
            {"0OR", "Smart Anytime Return"},
            {"0OS", "Smart Anytime Single"},
            {"10A", "Carnet Off-Peak Single"},
            {"10B", "Carnet Off-Peak Single (1st Class)"},
            {"10F", "Carnet (1st Class)"},
            {"10S", "Carnet (Standard)"},
            {"1AB", "Advance Single (1st Class)"},
            {"1AF", "Advance Single (1st Class)"},
            {"1AS", "Advance Single (1st Class)"},
            {"1BB", "Advance Single (1st Class)"},
            {"1BF", "Advance Single (1st Class)"},
            {"1BR", "First Bus &amp; Rail Card"},
            {"1BS", "Advance Single (1st Class)"},
            {"1CB", "Advance Single (1st Class)"},
            {"1CF", "Advance Single (1st Class)"},
            {"1CS", "Advance Single (1st Class)"},
            {"1DB", "Advance Single &amp; breakfast (1st Class)"},
            {"1DF", "Advance Single (1st Class)"},
            {"1DR", "Off-Peak Day Return"},
            {"1DS", "Advance Single (1st Class)"},
            {"1DT", "Off-Peak Day Travelcard"},
            {"1EF", "Advance Single (1st Class)"},
            {"1ES", "Advance Single (1st Class)"},
            {"1FA", "Club Solo"},
            {"1FB", "Club Solo"},
            {"1FF", "Advance Single (1st Class)"},
            {"1FS", "Advance Single (1st Class)"},
            {"1GA", "Fixed Club Solo"},
            {"1GB", "Fixed Club Solo"},
            {"1GF", "Advance Single (1st Class)"},
            {"1GS", "Advance Single (1st Class)"},
            {"1HF", "Advance Single (1st Class)"},
            {"1HS", "Advance Single (1st Class)"},
            {"1JF", "Advance Single (1st Class)"},
            {"1JS", "Advance Single (1st Class)"},
            {"1KF", "Advance Single (1st Class)"},
            {"1KS", "Advance Single (1st Class)"},
            {"1LA", "1st Class Lounge Year"},
            {"1LD", "1st Class Lounge Day"},
            {"1LF", "Advance Single (1st Class)"},
            {"1LM", "1st Class Lounge Month"},
            {"1LW", "1st Class Lounge Week"},
            {"1PS", "Cardiff Day"},
            {"1SA", "Sleeper Berth (1st Class)"},
            {"1SB", "Sleeper Berth (1st Class)"},
            {"1SC", "Sleeper Berth (1st Class)"},
            {"1SD", "Sleeper Berth (1st Class)"},
            {"1SE", "Sleeper Berth (1st Class)"},
            {"1SO", "Super Off-Peak Return (1st Class)"},
            {"1SS", "Super Off-Peak Single (1st Class)"},
            {"1ST", "Super Off-Peak Day Travelcard (1st Class)"},
            {"1VF", "VTWC Family Return (1st Class)"},
            {"1WK", "n-Network 1st Plus 1 Week"},
            {"24A", "CDR 2for1"},
            {"24B", "CDS 2for1"},
            {"24C", "SVR 2for1"},
            {"24D", "SDR 2for1"},
            {"24E", "SOS 2for1"},
            {"24F", "SDS 2for1"},
            {"24G", "FDR 2for1"},
            {"24H", "FDS 2for1"},
            {"24I", "FOR 2for1"},
            {"2AA", "Advance Single (promotion)"},
            {"2AF", "Advance Single"},
            {"2AS", "Advance Single"},
            {"2BF", "Advance Single"},
            {"2BS", "Advance Single"},
            {"2CC", "Advance Single"},
            {"2CF", "Advance Single"},
            {"2CS", "Advance Single"},
            {"2DC", "Advance Single"},
            {"2DF", "Advance Single"},
            {"2DS", "Advance Single"},
            {"2EC", "Advance Single"},
            {"2EF", "Advance Single"},
            {"2ES", "Advance Single"},
            {"2FB", "Advance Single"},
            {"2FC", "Advance Single"},
            {"2FF", "Advance Single"},
            {"2FI", "Advance Single"},
            {"2FS", "Advance Single"},
            {"2GB", "Advance Single"},
            {"2GC", "Advance Single"},
            {"2GF", "Advance Single"},
            {"2GI", "Advance Single"},
            {"2GS", "Advance Single"},
            {"2HC", "Advance Single"},
            {"2HF", "Advance Single"},
            {"2HS", "Advance Single"},
            {"2IA", "Advance Single"},
            {"2IB", "Advance Single"},
            {"2IC", "Advance Single"},
            {"2ID", "Advance Single"},
            {"2IE", "Advance Single"},
            {"2IF", "Advance Single"},
            {"2IG", "Advance Single"},
            {"2IH", "Advance Single"},
            {"2II", "Advance Single"},
            {"2IJ", "Advance Single"},
            {"2IS", "Advance Single"},
            {"2JC", "Advance Single"},
            {"2JF", "Advance Single"},
            {"2JS", "Advance Single"},
            {"2KC", "Advance Single"},
            {"2KF", "Advance Single"},
            {"2KS", "Advance Single"},
            {"2LC", "Advance Single"},
            {"2MC", "Advance Single"},
            {"2MF", "Advance Single"},
            {"2NF", "Advance Single"},
            {"2SA", "Stena Advance Peak"},
            {"2SO", "Stena Advance Off-Peak"},
            {"2SP", "Stena Standby Peak"},
            {"2SS", "Stena Standby Off-Peak"},
            {"3DS", "3 Day Season"},
            {"3PF", "VTEC Promotion Single (1st Class)"},
            {"3PS", "VTEC Promotion Single (Std Class)"},
            {"42R", "Four for Two Return"},
            {"42S", "Four for Two Single"},
            {"43R", "Group 5 Return"},
            {"43S", "Group 5 Single"},
            {"44R", "Group Return"},
            {"44S", "Group Single"},
            {"4DS", "4 Day Season"},
            {"4WK", "n-Network 1st Plus 4 Weeks"},
            {"55C", "Club 55 Hull Trains (1st Class)"},
            {"55D", "Club 55 Hull Trains Standard"},
            {"55E", "Club 55 Excess"},
            {"55F", "Club 55 (1st Class)"},
            {"55O", "Club 55 Website"},
            {"55P", "Club 55 Any Day"},
            {"55S", "Club 55 Standard"},
            {"55W", "Club 55 Not valid on Fridays"},
            {"7AF", "7 Day Season Ticket (1st Class)"},
            {"7AS", "7 Day Season Ticket"},
            {"7BR", "7 Day Bus &amp; Rail Card"},
            {"7BS", "Bus 7 Days Season"},
            {"7CA", "7 Day County Card"},
            {"7CT", "Network 1 Week"},
            {"7D1", "Anglia Plus 7 Days (1st Class)"},
            {"7DA", "Anglia Plus 7 Days "},
            {"7DF", "7 Day Season Ticket (1st Class)"},
            {"7DS", "7 Day Season Ticket"},
            {"7FF", "7 Day Fixed (1st class)"},
            {"7FS", "7 Day Fixed (standard)"},
            {"7PS", "Cardiff Seven"},
            {"7TF", "7 Day Travelcard Season (1st Class)"},
            {"7TS", "7 Day Travelcard Season Ticket"},
            {"98X", "ITX Package (1st Class)"},
            {"98Y", "ITX Package"},
            {"A02", "Anglia Plus 1 Month"},
            {"A03", "Anglia Plus 12 Months"},
            {"A04", "Anglia Plus 1 Month (1st Class)"},
            {"A05", "Anglia Plus 12 Months (1st Class)"},
            {"A40", "Sleeper Family Advance Single 4"},
            {"A41", "Sleeper Family Advance Single 4"},
            {"A42", "Sleeper Family Advance Single 4"},
            {"A43", "Sleeper Family Advance Single 4"},
            {"A44", "Sleeper Family Advance Single 4"},
            {"A60", "Sleeper Family Advance Single 6"},
            {"A61", "Sleeper Family Advance Single 6"},
            {"A62", "Sleeper Family Advance Single 6"},
            {"A63", "Sleeper Family Advance Single 6"},
            {"A64", "Sleeper Family Advance Single 6"},
            {"AA1", "Airport Advance Single (1st Class)"},
            {"AA2", "Airport Advance Single"},
            {"AAB", "Anytime Day Return"},
            {"AB1", "Airport Advance Single (1st Class)"},
            {"AB2", "Airport Advance Single"},
            {"ACP", "n-Network 1st Plus Annual"},
            {"ACS", "n-Network Annual"},
            {"AD1", "Airport Advance Single (1st Class)"},
            {"ADC", "Admission Concession 1 Month"},
            {"ADM", "Admission 1 Month"},
            {"ADT", "Anytime Day Travelcard"},
            {"AE1", "Airport Advance Single (1st Class)"},
            {"AF1", "Airport Advance Single (1st Class)"},
            {"AFS", "Greater Anglia 1st Class Supplement"},
            {"AG1", "Airport Advance Single (1st Class)"},
            {"AG2", "Airport Advance Single"},
            {"AH1", "Airport Advance Single (1st Class)"},
            {"AH2", "Airport Advance Single"},
            {"AI1", "Airport Advance Single (1st Class)"},
            {"AI2", "Airport Advance Single"},
            {"AJ1", "Airport Advance Single (1st Class)"},
            {"AJ2", "Airport Advance Single"},
            {"AK1", "Airport Advance Single (1st Class)"},
            {"AK2", "Airport Advance Single"},
            {"AL2", "Airport Advance Single"},
            {"ALO", "Loyalty Off-Peak Return"},
            {"ALP", "Alpamare Admittance ticket only"},
            {"AM1", "Super Off-Peak Day Single"},
            {"AM2", "Super Off-Peak Day Return"},
            {"AM3", "Super Off-Peak Day Travelcard"},
            {"AN2", "Airport Advance Single"},
            {"AO2", "Airport Advance Single"},
            {"AP2", "Airport Advance Single"},
            {"APR", "3 Day Apex"},
            {"AQ2", "Advance Single"},
            {"AR1", "Rail-Air Return (1st Class)"},
            {"AR2", "Rail-Air Return"},
            {"ARM", "n-Network Annual"},
            {"ARN", "ATW Rugby Train 2"},
            {"ARR", "ATW Rugby Train 1"},
            {"AS1", "Rail-Air Single (1st Class)"},
            {"AS2", "Rail-Air Single"},
            {"ASV", "Advance Single"},
            {"ATS", "Ascot 10.00GBP Voucher"},
            {"ATT", "Ascot 5.00GBP Voucher"},
            {"ATV", "ASC GBP5.00 Voucher"},
            {"ATY", "Arriva Ten Years"},
            {"AVK", "Advance Promo Single"},
            {"AVL", "Advance Promo Single (1st Class) "},
            {"AVM", "Advance Promo Single"},
            {"AVN", "Advance Promo Single (1st Class)"},
            {"AVO", "Advance Single (promo)"},
            {"AVP", "Advance Single (promotion)"},
            {"AVR", "Promotional Return"},
            {"AW1", "Advance Single (1st Class)"},
            {"AWR", "ATW Reservation"},
            {"AXS", "Advance Single"},
            {"B1R", "Business Return (1st Class)"},
            {"B1S", "Business Single (1st Class)"},
            {"B2R", "Business Return"},
            {"B2S", "Business Single"},
            {"BAO", "Advance Single"},
            {"BAS", "Bus Annual Season"},
            {"BB4", "Big Bus 48 hours"},
            {"BBB", "IRS Solo Sleeper"},
            {"BBO", "Advance Single"},
            {"BBT", "Big Bus 24 Hours"},
            {"BC1", "Business Carnet (1st Class)"},
            {"BC2", "Business Carnet"},
            {"BCF", "Friends &amp; Family"},
            {"BCO", "Advance Single"},
            {"BCP", "Berth Clean Pets"},
            {"BCR", "Business Class Return"},
            {"BCS", "Business Class Single"},
            {"BD1", "Business Carnet (1st Class)"},
            {"BD2", "Business Carnet"},
            {"BDA", "Stena Day Return"},
            {"BDD", "Busmaster Term"},
            {"BDO", "Advance Single"},
            {"BDR", "Bus Day Return"},
            {"BDS", "Bus Day Single"},
            {"BDU", "EMT 1st Class Upgrade"},
            {"BED", "Busmaster 52 weeks"},
            {"BFO", "Advance Single (1st Class)"},
            {"BFR", "Off-Peak Return (1st Class)"},
            {"BFS", "Off-Peak Single (1st Class)"},
            {"BG1", "Business Groupsave"},
            {"BGO", "Advance Single (1st Class)"},
            {"BHO", "Advance Single (1st Class)"},
            {"BJD", "Vigrin Trains West Coast Staff"},
            {"BMA", "Busmaster 52 Week"},
            {"BMB", "Bus+Metro Direct Debit M"},
            {"BMC", "NBus Direct Debit Month"},
            {"BMJ", "Bus Multi Journey"},
            {"BMS", "Bus Season 1 Month"},
            {"BOP", "Carnet Off-Peak"},
            {"BOR", "Bus Open Return"},
            {"BP1", "Business Plus Single"},
            {"BP2", "Business Plus Return"},
            {"BPH", "Off-Peak Day Return (high)"},
            {"BPL", "Off-Peak Day Return"},
            {"BPR", "Bus Period Return"},
            {"BPS", "Advance Single"},
            {"BQS", "Bus Season 3 Months"},
            {"BRR", "Standard Off-Peak 1 Return"},
            {"BRS", "Advance Single"},
            {"BS1", "One Day London Bus &amp; Tram Pass"},
            {"BSS", "Advance Single"},
            {"BSZ", "Advance Single"},
            {"BT1", "7-Day Bus &amp; Tram Pass"},
            {"BT2", "1 Month Bus &amp; Tram Pass"},
            {"BTS", "Advance Single"},
            {"BUS", "Advance Single"},
            {"BVR", "Off-Peak Return"},
            {"BVS", "Off-Peak Single"},
            {"BVV", "Bure Valley Railway"},
            {"BXS", "Advance Single"},
            {"BXZ", "Advance Single"},
            {"BYS", "Advance Single"},
            {"BZ1", "Business Zone Supplement"},
            {"BZ2", "Business Zone Supplement"},
            {"BZS", "Advance Single"},
            {"C13", "Network 13 Week"},
            {"C14", "Network 2 Week Off-Peak"},
            {"C1R", "Super Off-Peak Day Return"},
            {"C1S", "Advance Single"},
            {"C1X", "Advance Single"},
            {"C28", "Network 4 Week"},
            {"C2R", "Group Super Off-Peak Day Return"},
            {"C2S", "Advance Single"},
            {"C2W", "Network 2 Week Add-On"},
            {"C2X", "Advance Single"},
            {"C3S", "Advance Single"},
            {"C3X", "Advance Single"},
            {"C3Y", "Advance Single"},
            {"C4B", "Advance Single"},
            {"C4S", "Advance Single"},
            {"C4W", "Network 4 Week Add-On"},
            {"C4X", "Advance Single"},
            {"C4Y", "Advance Single"},
            {"C5B", "Advance Single"},
            {"C5X", "Advance Single"},
            {"C5Y", "Advance Single"},
            {"C6B", "Advance Single"},
            {"C6Y", "Advance Single"},
            {"C6Z", "Advance Single"},
            {"C7B", "Advance Single"},
            {"C7S", "Advance Single"},
            {"C7Z", "Advance Single"},
            {"C8B", "Advance Single"},
            {"C8Z", "Advance Single"},
            {"CA1", "NXEA Carnet 1st"},
            {"CA2", "NXEA Carnet Standard"},
            {"CA3", "Carnet Single"},
            {"CA4", "Carnet Single (1st Class)"},
            {"CA5", "Carnet 10"},
            {"CA6", "Carnet 20"},
            {"CA7", "Carnet 60"},
            {"CA8", "Carnet 100"},
            {"CAA", "Carnet 5 Standard"},
            {"CAB", "Carnet 5 (1st Class)"},
            {"CAC", "Carnet 5 Plus"},
            {"CAF", "Carnet 10 (1st Class)"},
            {"CAG", "Carnet 10 Standard"},
            {"CAH", "Leisure Carnet"},
            {"CAN", "Network 52 Week Add-On"},
            {"CAR", "Carnet Manchester Airport"},
            {"CAS", "Carnet 5 Standard"},
            {"CAV", "Carnet 5 (1st Class)"},
            {"CB1", "Cabin/Berth for one"},
            {"CBA", "Super Off-Peak Day Return"},
            {"CBB", "Super Off-Peak Single"},
            {"CC5", "Off-Peak Carnet 10"},
            {"CC6", "Off-Peak Carnet 20"},
            {"CC7", "Off-Peak Carnet 60"},
            {"CC8", "Off-Peak Carnet 100"},
            {"CCB", "Carnet Twelve"},
            {"CCR", "Scotrail Concession Return"},
            {"CCS", "Scotrail Concession Single"},
            {"CDE", "Soccerbus Season"},
            {"CDR", "Off-Peak Day Return"},
            {"CDS", "Off-Peak Day Single"},
            {"CE2", "Special Events"},
            {"CEF", "Special Events"},
            {"CEI", "Events Off-Peak Single (First Class)"},
            {"CES", "Events Off-Peak Single"},
            {"CFF", "Child Flat Fare Return"},
            {"CFP", "Red Dot Day"},
            {"CFS", "Kids-for-a-Quid Single"},
            {"CFT", "Club 50 Flat Fare Return"},
            {"CH1", "GWR ITX High 1st"},
            {"CH2", "GWR ITX High (Std)"},
            {"CHA", "Charter Return"},
            {"CHR", "Cheltenham Races Bus"},
            {"CL1", "GWR ITX Low 1st"},
            {"CL2", "GWR ITX Low (Std)"},
            {"CLA", "3-5 Admittance Only"},
            {"CLS", "Cityline Promotion"},
            {"CM1", "GWR ITX Medium 1st"},
            {"CM2", "GWR ITX Medium (Std)"},
            {"CME", "Chiltern Metro"},
            {"CMR", "Off-Peak Cracker"},
            {"CNE", "Connect Carnet"},
            {"CNF", "Gatwick Express Carnet 1st Class"},
            {"CNM", "Cheltenham Student"},
            {"CNP", "Carnet Peak"},
            {"CNR", "Concession Return"},
            {"CNS", "Concession Single"},
            {"CNT", "Gatwick Express Carnet Standard Class"},
            {"CO5", "Carnet Off-Peak 5"},
            {"COA", "Grand Central Complementary (1st Class)"},
            {"COB", "Grand Central Complementary (Std Class)"},
            {"COH", "Coach Link"},
            {"COL", "Southern Complementary Return (1st Class)"},
            {"COM", "Southern Complementary Return"},
            {"COP", "Carnet Off-Peak"},
            {"COR", "WAG Concession Return"},
            {"COS", "WAG Concession Single"},
            {"CP5", "Carnet Peak 5"},
            {"CPF", "Corporate Return (1st Class)"},
            {"CPP", "Carnet Peak"},
            {"CPR", "Cheap Park &amp; Ride"},
            {"CPS", "Corporate Return"},
            {"CQP", "Carnet Off-Peak"},
            {"CR1", "Charter Return (1st Class)"},
            {"CR2", "Charter Return (Standard)"},
            {"CRF", "Business Return (1st Class)"},
            {"CRT", "Carnet Return"},
            {"CRU", "Business Return"},
            {"CS1", "Sleeper Supplement (1st Class)"},
            {"CS2", "Sleeper Supplement (Standard)"},
            {"CSA", "Network Student Add-On"},
            {"CST", "Cycle Season"},
            {"CSU", "Business Single"},
            {"CT1", "Sea Control Ticket"},
            {"CTM", "Network Child Term RM"},
            {"CTW", "Network Term Add-On"},
            {"CWR", "Wally Rover"},
            {"CYC", "Cycle Fee"},
            {"CZS", "Zoo Student"},
            {"DAA", "DTPR Plus"},
            {"DAF", "Family DTPR Plus"},
            {"DAS", "Advance Single (1st Class)"},
            {"DBS", "Advance Single (1st Class)"},
            {"DCS", "Advance Single (1st Class)"},
            {"DDO", "Dublin Day Out"},
            {"DDS", "Advance Single (1st Class)"},
            {"DEF", "DTPR Family Exchange"},
            {"DES", "Advance Single (1st Class)"},
            {"DF1", "Advance Single (1st Class)"},
            {"DF2", "Advance Single (1st Class)"},
            {"DF3", "Advance Single (1st Class)"},
            {"DF4", "Advance Single (1st Class)"},
            {"DF5", "Advance Single (1st Class)"},
            {"DF6", "Advance Single (1st Class)"},
            {"DFS", "Advance Single (1st Class)"},
            {"DG1", "Advance Single"},
            {"DG2", "Advance Single"},
            {"DG3", "Advance Single"},
            {"DG4", "Advance Single"},
            {"DG5", "Advance Single"},
            {"DG6", "Advance Single"},
            {"DG7", "Advance Single"},
            {"DG8", "Advance Single"},
            {"DG9", "Advance Single"},
            {"DGS", "Advance Single (1st Class)"},
            {"DHS", "Advance Single (1st Class)"},
            {"DJS", "Advance Single (1st Class)"},
            {"DKS", "Advance Single (1st Class)"},
            {"DLS", "Advance Single (1st Class)"},
            {"DPC", "Daily Carpark"},
            {"DPS", "Advance Single"},
            {"DRG", "Dalesrail Duo"},
            {"DRI", "Dalesrail Off-Peak Day Return"},
            {"DRS", "Special Cheap Day Return"},
            {"DS1", "DaySave"},
            {"DS4", "DaySave 4"},
            {"DSD", "Day Ranger"},
            {"DST", "Flexiday Season"},
            {"DTA", "DTPR Add-On"},
            {"DTE", "DTPR Exchange"},
            {"DTF", "Family DTPR Add-On"},
            {"DTP", "Off Peak Day Travelcard PLUS"},
            {"DUO", "Greater Anglia Duo Return"},
            {"DUS", "Duo Single"},
            {"E1R", "Anytime Return"},
            {"E1S", "Anytime Single"},
            {"E2R", "Anytime Day Return"},
            {"E2S", "Anytime Day Single"},
            {"E3R", "Anytime Short Distance Return"},
            {"E4R", "Off-Peak Day Return"},
            {"E4S", "Off-Peak Day Single"},
            {"EAR", "Advance Return (CIV)"},
            {"EAS", "Advance Single (CIV)"},
            {"EBP", "Early Bird Plus"},
            {"ECD", "Evening Return"},
            {"ECR", "Economy Return"},
            {"ECS", "Economy Single"},
            {"EDA", "Bus/Admission Only"},
            {"EDF", "Admit Only Youth"},
            {"EDR", "Day Return"},
            {"EDS", "Day Single"},
            {"EFR", "Euro Anytime Return (1st Class)"},
            {"EGF", "Super Off-Peak Day Return"},
            {"EGG", "SWT Promotion Day Return"},
            {"EGH", "SWT Promo Day Single"},
            {"EGP", "Super Off-Peak Day Group"},
            {"EGS", "Super Off-Peak Day Single"},
            {"EIF", "Advance Single ITX (1st Class)"},
            {"EIS", "Advance Single ITX"},
            {"EJA", "Easyjet Advance Single (1st Class)"},
            {"EJB", "Easyjet Advance Return (1st Class)"},
            {"EJC", "Easyjet Advance Single"},
            {"EJD", "Easyjet Advance Return"},
            {"ELF", "Euro Leisure First Return (CIV)"},
            {"ELR", "Euro Low Saver Return (CIV)"},
            {"ELS", "Euro Low Saver Single (CIV)"},
            {"ELV", "Elvis Exhibition"},
            {"EM0", "EMT ITX High 1st"},
            {"EM2", "EMT ITX High"},
            {"EM3", "EMT ITX Medium1 "},
            {"EM4", "EMT ITX Medium"},
            {"EM5", "EMT ITX Low 1"},
            {"EM6", "EMT ITX Low"},
            {"EMB", "Business Return"},
            {"EMD", "Business Off-Peak Return"},
            {"EME", "Business Standard Return"},
            {"EMT", "EMT Promotion"},
            {"EOR", "Euro Anytime Return"},
            {"ES1", "Eurostar ITX 1st Class"},
            {"ES2", "Eurostar ITX Standard"},
            {"ES3", "Domestic ITX 1st Class"},
            {"ES4", "Domestic ITX Standard"},
            {"ESC", "Evening Standard Child"},
            {"ESP", "EuroVoyager Supplement"},
            {"ETR", "Executive Return Package 1st"},
            {"EVE", "Special Events"},
            {"EVF", "Special Events"},
            {"EVR", "Euro High Saver Return (CIV)"},
            {"EVS", "Euro High Saver Single (CIV)"},
            {"EWR", "Alphaline Return"},
            {"EXR", "5 Night Excursion"},
            {"EXV", "Exchange Voucher"},
            {"F1A", "Advance Single (1st Class)"},
            {"F1F", "Family &amp; Friends 1st"},
            {"F1L", "Flexipass Carnet"},
            {"F1V", "Advance Single (1st Class)"},
            {"F2A", "Advance Single (1st Class)"},
            {"F2F", "Family &amp; Friends (Standard)"},
            {"F2L", "Flexipass Carnet"},
            {"F2V", "Advance Single (1st Class)"},
            {"F3A", "Advance Single (1st Class)"},
            {"F3V", "Advance Single (1st Class)"},
            {"F4A", "Advance Single (1st Class)"},
            {"F4V", "Advance Single (1st Class)"},
            {"F5A", "Advance Single (1st Class)"},
            {"F6A", "Advance Single (1st Class)"},
            {"F7A", "Advance Single (1st Class)"},
            {"F7V", "Advance Single (1st Class)"},
            {"F8A", "Advance Single (1st Class)"},
            {"F9A", "Advance Single (1st Class)"},
            {"FAS", "Advance Single (1st Class)"},
            {"FAV", "Advance Single (1st Class)"},
            {"FAW", "FAW Anytime Day Return"},
            {"FB0", "Sleeper Berth Advance Single (1st Class)"},
            {"FB1", "Sleeper Berth Advance Single (1st Class)"},
            {"FB2", "Sleeper Berth Advance Single (1st Class)"},
            {"FB3", "Sleeper Berth Advance Single (1st Class)"},
            {"FB4", "Sleeper Berth Advance Single (1st Class)"},
            {"FBD", "Bus Day Rover"},
            {"FBM", "Bus Monthly"},
            {"FBS", "Advance Single (1st Class)"},
            {"FBV", "Advance Single (1st Class)"},
            {"FBW", "Bus Weekly"},
            {"FC1", "GWR Corporate Single (1st Class)"},
            {"FC2", "GWR Corporate Return (1st Class)"},
            {"FC3", "GWR Corporate Single"},
            {"FC4", "GWR Corporate Return"},
            {"FCB", "Group Return (1st Class)"},
            {"FCD", "Off-Peak Day Return (1st Class)"},
            {"FCF", "GTW Valid 42R1"},
            {"FCP", "Group 5 Return (1st Class)"},
            {"FCR", "Off-Peak Day Return (1st Class)"},
            {"FCS", "Advance Single (1st Class)"},
            {"FCU", "1st Upgrade Single"},
            {"FCV", "1st Upgrade Return"},
            {"FCW", "Concession Anytime Day Return"},
            {"FDA", "Kids Go Free 1"},
            {"FDB", "Kids Go Free 2"},
            {"FDC", "Kids Go Free 1"},
            {"FDD", "Kids Go Free 2"},
            {"FDR", "Anytime Day Return (1st Class)"},
            {"FDS", "Anytime Day Single (1st Class)"},
            {"FDT", "Anytime Day Travelcard (1st Class)"},
            {"FDV", "Advance Single (1st Class)"},
            {"FES", "Ffestiniog Round Robin"},
            {"FFA", "Group 5 Single (1st Class)"},
            {"FFC", "Family &amp; Friends Additional Child"},
            {"FFF", "GWT Valid FOR4S"},
            {"FFL", "Flexipass Carnet (1st Class)"},
            {"FFM", "Ffestiniog Round Robin Family"},
            {"FFO", "Flat Fare Super Off-Peak Return"},
            {"FFP", "Virgin Trains West Coast Flat Fare Single (1st Class)"},
            {"FFR", "Chiltern Railways Family Ticket"},
            {"FFS", "Family Return"},
            {"FFT", "GTW Valid 42S1"},
            {"FFW", "FAW Day Return (1st Class)"},
            {"FFX", "Flexipass 10 (1st Class)"},
            {"FFY", "Group Single (1st Class)"},
            {"FG3", "Anytime Group 3"},
            {"FG4", "Anytime Group 4"},
            {"FG5", "Anytime Group 5"},
            {"FGR", "Anytime Return (1st Class)"},
            {"FGS", "Anytime Single (1st Class)"},
            {"FHR", "Anytime Short Distance Return (1st Class)"},
            {"FIS", "Advance Single (1st Class)"},
            {"FMM", "Travelmaster 28 Days (1st Class)"},
            {"FMR", "Falmouth 150 Return"},
            {"FMS", "Falmouth 150 Single"},
            {"FMW", "Travelmaster 7 Days (1st Class)"},
            {"FND", "Northern Deal"},
            {"FNW", "Northern Duo"},
            {"FOR", "Anytime Return (1st Class)"},
            {"FOS", "Anytime Single (1st Class)"},
            {"FP1", "Flexipass Carnet"},
            {"FP2", "Flexipass Carnet"},
            {"FPL", "VTEC Group Single (1st Class)"},
            {"FPP", "First + Parking"},
            {"FPR", "Hay Festival Family"},
            {"FPT", "Hay Festival Family"},
            {"FPW", "Sleeper Flexipass"},
            {"FPX", "Flexipass 10 Sleeper 1st Class"},
            {"FPZ", "Classic Flexipass"},
            {"FRX", "Off-Peak Day Return (1st Class)"},
            {"FS0", "Fixed Seat Advance Single"},
            {"FS1", "Fixed Seat Advance Single"},
            {"FSA", "Super Off-Peak Day Single (1st Class)"},
            {"FSB", "Super Off-Peak Day Return (1st Class)"},
            {"FSC", "Super Off-Peak Day Travelcard (1st Class)"},
            {"FSL", "Flexipass Carnet"},
            {"FSO", "Off-Peak Day Return (1st Class)"},
            {"FSP", "Firstgroup Staff Promotion"},
            {"FSR", "Off-Peak Return (1st Class)"},
            {"FSS", "Off-Peak Single (1st Class)"},
            {"FST", "Football ST"},
            {"FSX", "Off-Peak Single (1st Class)"},
            {"FTA", "GWT Valid for 2R"},
            {"FTB", "GWT Valid For 3R"},
            {"FTC", "Off-Peak Family Travelcard"},
            {"FTD", "GTW Valid for 4R"},
            {"FTF", "GWT valid for 3S"},
            {"FTP", "Off-Peak Day Travelcard PLUS (1st Class)"},
            {"FTR", "Web Off-Peak Day Travelcard 1st"},
            {"FTS", "FCC TfL Priv"},
            {"FTT", "GWT Valid for 2S"},
            {"FTX", "Off-Peak Day Travelcard (1st Class)"},
            {"FUS", "Rail Staff Travel Single (1st Class)"},
            {"FWE", "GWR Weekend Explorer"},
            {"FWF", "GWR Weekend Upgrade"},
            {"FXC", "Family Cracker"},
            {"FXR", "Advance Single (1st Class)"},
            {"FXS", "Advance Single (1st Class)"},
            {"FZL", "Scilly Island Long Stay"},
            {"FZP", "Sale First"},
            {"FZS", "Scilly Island Short Stay"},
            {"G10", "VTEC Weekend First Supplement"},
            {"G15", "VTEC Weekday 1st Supplement"},
            {"G1R", "Off-Peak Return (1st Class)"},
            {"G1S", "Off-Peak Single (1st Class)"},
            {"G1Y", "Grand Central Promotion 1Y"},
            {"G1Z", "Granc Central Promotion 1Z"},
            {"G2F", "Flyaway Return (2 persons)"},
            {"G2R", "Off-Peak Return"},
            {"G2S", "Off-Peak Single"},
            {"G2T", "Web Duo Anytime Return"},
            {"G3F", "Flyaway Return (3 persons)"},
            {"G4D", "Group 4 Day Return"},
            {"G4F", "Flyaway Return (4 persons)"},
            {"GA1", "GA Promotion Single"},
            {"GA2", "Group Advance 02"},
            {"GA5", "Group Advance 05"},
            {"GAT", "Megabus Plus"},
            {"GAX", "Group Advance 10"},
            {"GB1", "Value 5 Pounds"},
            {"GC3", "Advance Single (1st Class)"},
            {"GC4", "Advance Single (1st Class)"},
            {"GC5", "Advance Single (1st Class)"},
            {"GC6", "Advance Single (1st Class)"},
            {"GC7", "Advance Single (1st Class)"},
            {"GC8", "Advance Single (1st Class)"},
            {"GCA", "Advance Single (1st Class)"},
            {"GCB", "Advance Single"},
            {"GCD", "Advance Single"},
            {"GCE", "Advance Single (1st Class)"},
            {"GCF", "Grand Central Family &amp; Friends"},
            {"GCG", "Advance Single"},
            {"GCH", "Advance Single"},
            {"GCI", "Advance Single"},
            {"GCJ", "Advance Single"},
            {"GCK", "Grand Central Kids Go Free"},
            {"GCL", "Granc Central Kids Go Free 2"},
            {"GCP", "Grand Central Promotion"},
            {"GCQ", "Advance Single"},
            {"GCR", "Advance Single"},
            {"GCS", "Advance Single"},
            {"GCT", "Advance Single"},
            {"GCU", "Advance Single"},
            {"GCV", "Advance Single"},
            {"GCX", "Grand Central Promotion X"},
            {"GCY", "Grand Central Promo Y"},
            {"GCZ", "Grand Central Promotion Z"},
            {"GDR", "Super Off-Peak Day Return"},
            {"GDS", "Super Off-Peak Day Single"},
            {"GE1", "Off-Peak Day Return (1st Class)"},
            {"GEU", "O2 1st Upgrade"},
            {"GF1", "Flyaway Return (1 person)"},
            {"GF3", "Group 3 Advance Single"},
            {"GF4", "Group 4 Advance Single"},
            {"GF5", "Group 5 Advance Single"},
            {"GF7", "7-Day Season"},
            {"GFD", "Day Return"},
            {"GFR", "Anytime Return (1st Class)"},
            {"GFS", "Anytime Single (1st Class)"},
            {"GGG", "NRS Test Group"},
            {"GGW", "Goodwood Races"},
            {"GGX", "Glorious Goodwood"},
            {"GLR", "Glastonbury Festival Single"},
            {"GLS", "Glastonbury Festival Return"},
            {"GMM", "TfM 1 Month Traincard "},
            {"GMW", "TfM 7 Day Traincard"},
            {"GMY", "TfM Annual Traincard"},
            {"GO3", "EMT Group Off-Peak 3"},
            {"GO5", "EMT Group Off-Peak 5"},
            {"GOR", "Anytime Return"},
            {"GP1", "EMT Group (1st Class)"},
            {"GP2", "EMT Group (Standard)"},
            {"GP3", "EMT Group Peak 3"},
            {"GP5", "EMT Group Peak 5"},
            {"GPA", "ITX High 1st Class"},
            {"GPB", "ITX 1st Medium"},
            {"GPC", "ITX 1st Low"},
            {"GPD", "ITX High Standard"},
            {"GPE", "ITX Std Medium"},
            {"GPF", "ITX Std Low"},
            {"GPR", "Anytime Day Return"},
            {"GPS", "Small Group Single"},
            {"GR3", "Groupsave Day Return 3"},
            {"GR4", "Groupsave Day Return 4"},
            {"GR5", "Groupsave Day Return 5"},
            {"GSK", "Groupsave Child"},
            {"GT3", "East Midlands Trains Group SOP3"},
            {"GT5", "East Midlands Trains Group SOP5"},
            {"GTR", "Anytime Return"},
            {"GTS", "Anytime Single"},
            {"GUR", "Anytime Return (1st Class)"},
            {"GUS", "Anytime Single (1st Class)"},
            {"GVR", "Anglo-Scottish Off-Peak Return"},
            {"GWC", "Carnet (1st Class)"},
            {"GWD", "Carnet (Standard)"},
            {"GXC", "1st Upgrade"},
            {"GXO", "1st Upgrade SOR"},
            {"GXR", "CDGE 1 Upgrade"},
            {"GXS", "1st Upgrade SOS"},
            {"GYA", "Great Yorkshire Show Adult Admit"},
            {"GYF", "Great Yorkshire Show Family Admit"},
            {"H1F", "Helicopter X 1"},
            {"HAA", "Bus &amp; Admission Only"},
            {"HAB", "Bus &amp; Admission Concession"},
            {"HAC", "Bus &amp; Admission Only"},
            {"HAD", "Bus &amp; Admission Concession"},
            {"HAE", "Bus&amp;Admission Toddler"},
            {"HAF", "Admission (Family)"},
            {"HAG", "Family Admit"},
            {"HAS", "Admission (Senior)"},
            {"HCA", "Admit 1 Film"},
            {"HCB", "Bus &amp; Admission"},
            {"HCD", "Admission Only Concession"},
            {"HCE", "Admission Only Student"},
            {"HCF", "Admission Only"},
            {"HCG", "2 Day Fri &amp; Sat"},
            {"HCH", "Admission Only (Senior)"},
            {"HCI", "Bus &amp; Admission (Youth)"},
            {"HCJ", "Bus &amp; Admission (Senior)"},
            {"HCK", "2 Day Sat &amp; Sun"},
            {"HCL", "Friday Preview"},
            {"HCM", "3 Day Admission"},
            {"HCN", "2 Day Family Admit"},
            {"HCO", "Lingfield Return Saturday"},
            {"HCP", "2 Day Admit Concession"},
            {"HCQ", "2 Day Admission"},
            {"HCR", "2 Day Fri &amp; Sun"},
            {"HCU", "Lingfield Races (Mon-Fri)"},
            {"HCV", "Epsom Live"},
            {"HCW", "1 Day Family Admit"},
            {"HCX", "2 Day Family Admit"},
            {"HEA", "Weekend Promo Single"},
            {"HEB", "Weekend Promo Return"},
            {"HEC", "Off-Peak Promo Single"},
            {"HED", "Off-Peak Promo Return"},
            {"HER", "Coach Return"},
            {"HES", "Coach Single"},
            {"HF2", "Family 2 Return"},
            {"HF3", "Family 3 Return"},
            {"HF4", "Family 4 Return"},
            {"HFC", "Admit Family"},
            {"HFF", "Admit Only Family"},
            {"HH1", "FHT ITX 1st Class High"},
            {"HH2", "FHT ITX Standard High"},
            {"HHH", "NRS High WE 1st"},
            {"HL1", "FHT ITX 1st Class Low"},
            {"HL2", "FHT ITX Standard Low"},
            {"HLC", "Bus &amp; Admittance Concession"},
            {"HMC", "Bus &amp; Admittance Family (1 Adult, 3 Children)"},
            {"HNC", "Bus &amp; Admittance Family (2 Adults, 2 Children)"},
            {"HOR", "Anytime Return"},
            {"HOS", "Anytime Single"},
            {"HPA", "HT Promo Advance Single"},
            {"HS7", "HS1 Free 7 Day"},
            {"HSR", "High Saver Return"},
            {"HT1", "Advance Single (1st Class)"},
            {"HT2", "Advance Single"},
            {"HT4", "Advance Single"},
            {"HTA", "Advance Single"},
            {"HTD", "Hull Trains Duo"},
            {"HTS", "Advance Single"},
            {"HTT", "Advance Single (1st Class)"},
            {"HU2", "Hull Trains Family 2"},
            {"HU3", "Hull Trains Family 3"},
            {"HU4", "Hull Trains Family 4"},
            {"HUA", "HS1 Upgrade Single"},
            {"HUB", "HS1 Upgrade Anytime"},
            {"HUC", "HS1 Upgrade Off-Peak"},
            {"HV0", "Fixed Day Single Standard"},
            {"HV1", "Fixed Day Single Standard"},
            {"HV2", "Fixed Day Single Standard"},
            {"HV3", "Fixed Day Single Standard"},
            {"HV4", "Fixed Day Single Standard"},
            {"HV5", "Fixed Day Single Standard"},
            {"HX1", "Anytime Day Single"},
            {"HX2", "Unaccompanied Child Single"},
            {"HX4", "Anytime Return"},
            {"HX7", "Off-Peak Day Single"},
            {"HX9", "DuoSaver Return"},
            {"HZ0", "Anytime Day Single (1st Class)"},
            {"HZ1", "Carnet 6"},
            {"HZ2", "Carnet 6 (1st Class)"},
            {"HZ3", "Carnet 12"},
            {"HZ4", "Carnet 12 (1st Class)"},
            {"HZ6", "Anytime Return (1st Class)"},
            {"I1A", "Advance Single (1st Class)"},
            {"I1B", "Advance Single (1st Class)"},
            {"I1C", "Advance Single (1st Class)"},
            {"I1D", "Advance Single (1st Class)"},
            {"I1E", "Advance Single (1st Class)"},
            {"I1F", "Advance Single (1st Class)"},
            {"I1G", "Advance Single (1st Class)"},
            {"I1H", "Advance Single (1st Class) &amp; breakfast"},
            {"I1I", "Advance Single (1st Class)"},
            {"IAB", "Advance Single (1st Class)"},
            {"IBB", "Advance Single (1st Class)"},
            {"ICB", "Advance Single (1st Class)"},
            {"IF1", "VTEC Advance Single ITX 1st Class"},
            {"IF3", "VTEX Advance Single ITX 1st Class"},
            {"IFR", "International 1st Return 2 month"},
            {"IFS", "International First Single"},
            {"IS0", "VTEC Advance Single ITX"},
            {"IS1", "VTEC Advance Single ITX"},
            {"IS3", "VTEC Advance Single ITX"},
            {"ISR", "International 2nd Return 2 month"},
            {"ISS", "International Second Single"},
            {"IT1", "NRS SAGA IT 1st"},
            {"IT2", "NRS SAGA IT Standard"},
            {"ITS", "International SuperAdvance"},
            {"IXF", "ITX Sleeper Single (1st Class)"},
            {"IXS", "ITX Sleeper Single (Standard Class)"},
            {"J2A", "Advance Single"},
            {"JAS", "Advance Single"},
            {"JBS", "Advance Single"},
            {"JCS", "Advance Single"},
            {"JDS", "Advance Single"},
            {"JES", "Advance Single"},
            {"JFS", "Advance Single"},
            {"JGS", "Advance Single"},
            {"JHS", "Advance Single"},
            {"K4Q", "Kids for a Quid Online"},
            {"K4R", "Child Flat Fare Return"},
            {"K4S", "Child Flat Fare Single"},
            {"KFF", "Child Flat Fare"},
            {"KFQ", "Child Flat Fare"},
            {"KGF", "Kids Go Free CDR"},
            {"L1R", "Launch Return (1st Class)"},
            {"L2R", "Launch Return"},
            {"LA1", "Advance Single (1st Class)"},
            {"LA2", "Advance Single"},
            {"LBT", "London Bus Tour"},
            {"LCF", "Leeds Festival"},
            {"LFB", "Advance Single (1st Class)"},
            {"LG2", "AGA Group 1st Single"},
            {"LG3", "AGA Group Standard Return"},
            {"LG4", "AGA Group 1st Return"},
            {"LG5", "AGA Group Standard Single"},
            {"LGR", "Leisure First"},
            {"LME", "GE PM Peak Supplement"},
            {"LMM", "Leisure Carnet"},
            {"LNO", "Super Off-Peak Day Return"},
            {"LNR", "Light Night"},
            {"LSR", "Low Saver Return (CIV)"},
            {"LSS", "Low Saver Single (CIV)"},
            {"LVR", "London Evening Out 2for1"},
            {"LYE", "Le Yorks 1D"},
            {"LYF", "Le Yorks 2D"},
            {"MAF", "Advance Single (1st Class)"},
            {"MAS", "Advance Single"},
            {"MBA", "First Breakfast"},
            {"MBB", "First Food"},
            {"MBC", "EMT Breakfast C"},
            {"MBD", "Refreshments"},
            {"MBF", "Advance Single (1st Class)"},
            {"MBS", "Advance Single"},
            {"MCA", "Metrocard Annual"},
            {"MCF", "Advance Single (1st Class)"},
            {"MCM", "Metrocard 1 Month"},
            {"MCQ", "Metrocard 3 Months"},
            {"MCS", "Advance Single"},
            {"MCW", "Metrocard 7 Day"},
            {"MDF", "Advance Single (1st Class)"},
            {"MDS", "Advance Single"},
            {"MEF", "Advance Single (1st Class)"},
            {"MES", "Advance Single"},
            {"MFB", "Monthly (1st Class)"},
            {"MFF", "Advance Single (1st Class)"},
            {"MFS", "Advance Single"},
            {"MGF", "Advance Single (1st Class)"},
            {"MGS", "Advance Single"},
            {"MHS", "Advance Single"},
            {"MIA", "Advance Single"},
            {"MIB", "Advance Single"},
            {"MID", "Super Off-Peak (Monday-Thursday)"},
            {"MIF", "Advance Single (1st Class)"},
            {"MIS", "Advance Single"},
            {"MJF", "Advance Single (1st Class)"},
            {"MJS", "Advance Single"},
            {"MKS", "MKBS Single"},
            {"MLA", "Metrolink 12 months"},
            {"MLM", "Metrolink 28 days"},
            {"MLW", "Metrolink 7 days"},
            {"MM1", "Moreton-in-Marsh Show Duo"},
            {"MM2", "Moreton-in-Marsh Show Family"},
            {"MMC", "EMT Carnet"},
            {"MMD", "EMT Carnet (1st Class)"},
            {"MML", "Leisure Carnet"},
            {"MMM", "NRS Medium WE 1st"},
            {"MMQ", "Multi-Flex 24"},
            {"MMR", "Mobile Multiflex"},
            {"MMS", "Advance Single"},
            {"MRM", "Railpass Monthly"},
            {"MRT", "Merthyr Rock"},
            {"MRW", "Railpass Weekly"},
            {"MRY", "Railpass Annual"},
            {"MSB", "Monthly Standard"},
            {"MSS", "Merseyrail Sunday Special Return"},
            {"MST", "Merseyrail Sunday Promo Return"},
            {"MSV", "ME Day Saver"},
            {"MSW", "Day Saver 16-18"},
            {"MTY", "MT Trio Year Season"},
            {"MXR", "Airport Apex 2"},
            {"NBA", "Advance Single"},
            {"NCA", "Advance Single"},
            {"ND1", "NTR Direct Debit Month"},
            {"ND2", "NTR Direct Debit Month 1st Class"},
            {"ND3", "NTR DD T Ex"},
            {"ND4", "Net DD Month"},
            {"ND5", "Net DD T Ex"},
            {"ND6", "Net DD Month 1"},
            {"ND7", "Net Add DD TX"},
            {"ND8", " Net Add DD M"},
            {"NDA", "Advance Single"},
            {"NDM", "NN pre 0930 DD"},
            {"NDN", "NT Pre 0930 DD"},
            {"NDR", "Special Day"},
            {"NDS", "Special Day"},
            {"NEA", "Advance Single"},
            {"NFT", "Not valid for travel"},
            {"NN1", "nNetwork 1 day"},
            {"NN2", "Daytripper"},
            {"NN3", "Daytripper Family"},
            {"NNR", "North Norfolk Railway"},
            {"NS1", "Southern 1st Supplement"},
            {"NT3", "Ntrain 3 Month"},
            {"NWM", "NWM Concession Admit"},
            {"NX1", "Advance Single (1st Class)"},
            {"NXO", "VTEC Flat Fare Single (1st Class)"},
            {"NXP", "VTEC Flat Fare Single"},
            {"O2C", "O2 Carnet"},
            {"O2R", "O2 2for1 Return (1st Class)"},
            {"OAS", "Advance Single (1st Class)"},
            {"OBS", "Advance Single (1st Class)"},
            {"OBZ", "Advance Single (1st Class)"},
            {"OC1", "Off-Peak Carnet (1st Class)"},
            {"OC2", "Off-Peak Carnet"},
            {"OCS", "Advance Single (1st Class)"},
            {"OCT", "Oxford Carnet Return"},
            {"OCZ", "Advance Single (1st Class)"},
            {"OD1", "Off-Peak Carnet (1st Class)"},
            {"OD2", "Off-Peak Carnet"},
            {"ODF", "First Bus &amp; Rail Card Family"},
            {"ODS", "Advance Single (1st Class)"},
            {"ODT", "Off-Peak Day Travelcard"},
            {"OES", "Advance Single (1st Class)"},
            {"OF1", "Advance Single (1st Class)"},
            {"OF2", "Advance Single (1st Class)"},
            {"OF3", "Advance Single (1st Class)"},
            {"OF4", "Advance Single (1st Class)"},
            {"OF5", "Advance Single (1st Class)"},
            {"OF6", "Advance Single (1st Class)"},
            {"OFY", "Advance Single (1st Class)"},
            {"OFZ", "Advance Single (1st Class)"},
            {"OGS", "Advance Single (1st Class)"},
            {"OHS", "Advance Single (1st Class)"},
            {"OJS", "Advance Single (1st Class)"},
            {"OLD", "Web Super Off-Peak Day Return"},
            {"OLS", "Off-Peak Return"},
            {"OLT", "Super Off-Peak Day Travelcard"},
            {"OMS", "Mag Strip"},
            {"OPB", "Super Off-Peak Day Return"},
            {"OPD", "Super Off-Peak Day Single"},
            {"OPF", "Off-Peak Day Return (1st Class)"},
            {"OPG", "Off-Peak Day Travelcard Group 10"},
            {"OPM", "Off-Peak Mini Group 3"},
            {"OPN", "Off-Peak Mini Group 4"},
            {"OPO", "Super Off-Peak Return (online)"},
            {"OPP", "Off-Peak Parking"},
            {"OPR", "Super Off-Peak Return"},
            {"OPS", "Super Off-Peak Single"},
            {"ORR", "Oyster Data"},
            {"OS1", "Advance Single"},
            {"OS2", "Advance Single"},
            {"OS3", "Advance Single"},
            {"OS4", "Advance Single"},
            {"OS5", "Advance Single"},
            {"OS6", "Advance Single"},
            {"OSB", "GA Business Return"},
            {"OSC", "Advance Single"},
            {"OSR", "Offshore Return"},
            {"OSY", "Advance Single"},
            {"OSZ", "Advance Single"},
            {"OTA", "One Ticket Annual"},
            {"OTF", "Off-Peak Day Travelcard (1st Class)"},
            {"OTM", "One Ticket Month"},
            {"OTU", "Oyster Top Up"},
            {"OTW", "One Ticket Week"},
            {"OVN", "Overnighter Return"},
            {"PAP", "PAYG Peak (for information only)"},
            {"PAR", "Argyle Return"},
            {"PAS", "Cardiff Annual"},
            {"PB7", "PlusBus 7 Day Pass"},
            {"PBA", "PlusBus Annual"},
            {"PBD", "PlusBus Day Pass"},
            {"PBM", "PlusBus Month"},
            {"PBQ", "PlusBus Quarter"},
            {"PBW", "Plusbus Web"},
            {"PCF", "Complimentary 1st Class"},
            {"PCS", "Complimentary Standard"},
            {"PCU", "ATW Premier Upgrade"},
            {"PDR", "Super Off-Peak Day Return"},
            {"PDS", "Super Off-Peak Day Single"},
            {"PFW", "Central Penalty Warning"},
            {"PLA", "Platform Ticket"},
            {"PMB", "PMT Bus Only Day"},
            {"PMP", "PMT Bus Only Period"},
            {"PMR", "Super Off-Peak Day Return"},
            {"PMS", "Cardiff Month"},
            {"PNE", "GWR Penalty Fare"},
            {"PNF", "Penalty Fare"},
            {"POP", "PAYG Off-Peak (for information only)"},
            {"PRA", "GMPTE Concessionary Fares Return"},
            {"PRT", "Pricebuster Return"},
            {"PSA", "GMPTE Concessionary Fares Single"},
            {"PSB", "Bus Period Season"},
            {"PSF", "Season Ticket (1st Class)"},
            {"PSG", "Pricebuster Single"},
            {"PSR", "Park and Ride"},
            {"PSS", "Season Ticket"},
            {"PSV", "Pricebuster Off-Peak Return"},
            {"PWS", "Penalty Fares Warning"},
            {"QAA", "Online Only CDR"},
            {"QAB", "Online CDS Offer"},
            {"QSV", "Online Only SVR"},
            {"QSW", "Online SVS Offer"},
            {"R01", "n-Train 30 Days (1st Class)"},
            {"R12", "12 in 20 Days Rover"},
            {"R14", "14 Day Rover"},
            {"R28", "n-Train 28 Days"},
            {"R29", "n-Train 29 Days"},
            {"R30", "n-Train 30 Days"},
            {"R71", "n-Train 7 Days (1st Class)"},
            {"R81", "n-Train 28 Days (1st Class)"},
            {"R91", "n-Train 29 Days (1st Class)"},
            {"RA1", "n-Train Annual (1st Class)"},
            {"RAD", "Off-Peak Day Ranger"},
            {"RAE", "Evening Ranger"},
            {"RCS", "TMR Walk Up 1st Class"},
            {"RDD", "Red Dot Day"},
            {"RF7", "NTrains 7-Day Cross-Boundary (1st Class)"},
            {"RFM", "Ntrain Period Season Cross Boundary (1st Class)"},
            {"RGP", "Day Ranger Group"},
            {"RGR", "Day Ranger"},
            {"RM7", "n-Train 7 Days"},
            {"RMA", "1st RM Season"},
            {"RMM", "Railmaster Month"},
            {"RMP", "Rail Master Period"},
            {"RP2", "Group Park &amp; Ride 2"},
            {"RP3", "Group Park &amp; Ride 3"},
            {"RP4", "Group Park &amp; Ride 4"},
            {"RPA", "Rail Pass Year 16-18"},
            {"RPM", "Rail Pass Month 16-18"},
            {"RPW", "Rail Pass Week 16-18"},
            {"RSS", "TMR Walk Up Standard"},
            {"RTM", "N-Train Term Extra"},
            {"RUG", "Wales Rugby Return"},
            {"RV3", "3 in 7 Days Rover"},
            {"RV4", "4 in 8 Days Rover"},
            {"RV8", "8 in 15 Days Rover"},
            {"RVE", "14 Day Rail Rover"},
            {"RVF", "Rover (1st Class)"},
            {"RVR", "Rover"},
            {"RX7", "Ntrain 7 Day X Boundary"},
            {"RXM", "NTrain Period Season Cross Boundary"},
            {"S01", "FSR Group 01"},
            {"S02", "FSR Group 02"},
            {"S03", "FSR Group 03"},
            {"S04", "FSR Group 04"},
            {"S05", "FSR Group 05"},
            {"S06", "FSR Group 06"},
            {"S07", "FSR Group 07"},
            {"S08", "FSR Group 08"},
            {"S09", "FSR Group 09"},
            {"S10", "FSR Group 10"},
            {"S11", "FSR Group 11"},
            {"S12", "FSR Group 12"},
            {"S13", "FSR Group 13"},
            {"S14", "FSR Group 14"},
            {"S15", "FSR Group 15"},
            {"S16", "FSR Group 16"},
            {"S17", "FSR Group 17"},
            {"S18", "FSR Group 18"},
            {"S19", "FSR Group 19"},
            {"S1A", "Advance Single"},
            {"S20", "FSR Group 20"},
            {"S2A", "Advance Single"},
            {"S3A", "Advance Single"},
            {"S4A", "Advance Single"},
            {"S5A", "Advance Single"},
            {"S6A", "Advance Single"},
            {"S7A", "Advance Single"},
            {"S8A", "Advance Single"},
            {"S9A", "Advance Single"},
            {"SAA", "Standard Single Cabin B"},
            {"SAB", "Sleeper Twin Single"},
            {"SAC", "Sleeper Solo Single"},
            {"SAD", "Sleeper Solo Single"},
            {"SAG", "Sleeper Advance Solo Single"},
            {"SAH", "Sleeper Advance Solo Single"},
            {"SAI", "Sleeper Advance Solo Single"},
            {"SAJ", "Sleeper Advance Solo Single"},
            {"SAK", "Sleeper Advance Solo Single"},
            {"SAL", "Sleeper Advance Solo Single"},
            {"SAM", "Sleeper Advance Twin Single"},
            {"SAN", "Sleeper Advance Twin Single"},
            {"SAO", "Sleeper Advance Twin Single"},
            {"SAP", "Sleeper Advance Twin"},
            {"SAQ", "Sleeper Advance Solo"},
            {"SAR", "Sleeper Advance Solo"},
            {"SAS", "Advance Single"},
            {"SAV", "Advance Single"},
            {"SAW", "Standard Single Cabin"},
            {"SAX", "Standard Cabin Not V"},
            {"SB0", "Sleeper Berth Advance Single"},
            {"SB1", "Sleeper Berth Advance Single"},
            {"SB2", "Sleeper Berth Advance Single"},
            {"SB3", "Sleeper Berth Advance Single"},
            {"SB4", "Sleeper Berth Advance Single"},
            {"SBD", "Sleeper Berth (standard)"},
            {"SBE", "Sleeper Berth (standard)"},
            {"SBF", "Sleeper Berth (standard)"},
            {"SBG", "Sleeper Berth (standard)"},
            {"SBH", "Sleeper Berth (standard)"},
            {"SBV", "Advance Single"},
            {"SCA", "Annual County Card"},
            {"SCF", "Friends and Family Day Return "},
            {"SCM", "Monthly County Card"},
            {"SCO", "Super Off-Peak Day Return"},
            {"SCP", "Smartcard Season Ticket"},
            {"SCV", "Advance Single"},
            {"SD1", "Southern Daysave Off-Peak"},
            {"SD4", "Southern Daysave Group Off-Peak"},
            {"SDF", "Daysave Flexi"},
            {"SDG", "7-Day Season Adult Rail Only"},
            {"SDH", "7-Day Season Child Rail Only"},
            {"SDI", "7-Day Season Adult with Inner Zone"},
            {"SDJ", "7-Day Season Child with Inner Zone"},
            {"SDK", "7-Day Season Adult With Inner &amp; Outer Zone"},
            {"SDL", "7-Day Season Child With Inner &amp; Outer Zone"},
            {"SDP", "Southern Daysave Peak"},
            {"SDR", "Anytime Day Return"},
            {"SDS", "Anytime Day Single"},
            {"SDT", "Senior Bus Day Return"},
            {"SDV", "Advance Single"},
            {"SDW", "Daysave Weekly"},
            {"SE1", "Family Super Economy"},
            {"SE3", "Group Single 3"},
            {"SE4", "Group Single 4"},
            {"SEA", "Football Season"},
            {"SEC", "SE Coast"},
            {"SED", "Stansted Express Duo Return"},
            {"SEE", "Advance Single"},
            {"SEF", "Advance Single"},
            {"SER", "Super Economy Return"},
            {"SES", "Super Economy Single"},
            {"SFA", "Web Off-Peak 1st"},
            {"SFB", "GWR Surfboard"},
            {"SFL", "SP Flower Show"},
            {"SFM", "Direct Debit 1Month Season"},
            {"SFN", "DD 1 Month Season Travelcard"},
            {"SFP", "Ferry Period Return"},
            {"SFR", "Ferry Day Return"},
            {"SFS", "Ferry Day Single"},
            {"SFX", "Flexipass 10 Standard"},
            {"SGA", "Small Group Advance"},
            {"SGD", "Small Group Day"},
            {"SGP", "Small Group Period"},
            {"SGR", "Super Advance"},
            {"SH0", "Sleeper Berth HF Advance"},
            {"SH1", "Sleeper Berth HF Advance"},
            {"SH2", "Sleeper Berth HF Advance"},
            {"SH3", "Sleeper Berth HF Advance"},
            {"SH4", "Sleeper Berth HF Advance"},
            {"SHF", "Shearings (1st Class)"},
            {"SHR", "Anytime Short Distance Return"},
            {"SHS", "Shearings (Standard)"},
            {"SI1", "Package 1st"},
            {"SI2", "Package Standard"},
            {"SIH", "Scilly Islands Helicopter"},
            {"SL1", "Stena Level 1"},
            {"SL2", "Stena Level 2"},
            {"SL3", "Stena Level 3"},
            {"SL4", "Stena Level 4"},
            {"SL5", "Stena Level 5"},
            {"SLA", "SailRail Advance Single"},
            {"SLD", "SailRail Standby Single"},
            {"SMG", "Skegness Promotion"},
            {"SMO", "TPE Staff Promotion"},
            {"SN2", "Southern Standard Su"},
            {"SNF", "Senior Flat Fare"},
            {"SNO", "Web Off-Peak Return"},
            {"SNP", "Web Off-Peak Return"},
            {"SNR", "Web Anytime Day Return"},
            {"SNS", "Web Off-Peak Single"},
            {"SNT", "Web Off-Peak Day Travelcard"},
            {"SNU", "Web Off-Peak Day Return (1st Class)"},
            {"SO3", "Smart Anytime Single"},
            {"SOA", "Super Off-Peak Day Single"},
            {"SOB", "Super Off-Peak Day Return"},
            {"SOC", "Super Off-Peak Day Single"},
            {"SOD", "Super Off-Peak Day Return"},
            {"SOE", "Super Off-Peak Day Travelcard"},
            {"SOF", "Super Off-Peak Day Return (1st Class)"},
            {"SOG", "Super Off-Peak Day Single"},
            {"SOH", "Super Off-Peak Day Return"},
            {"SOI", "Super Off-Peak Day Travelcard"},
            {"SOP", "Super Off-Peak Return"},
            {"SOR", "Anytime Return"},
            {"SOS", "Anytime Single"},
            {"SOT", "Super Off-Peak Day Travelcard"},
            {"SOW", "Weekend Super Off-Peak Day Return"},
            {"SOX", "Weekend Super Off-Peak Day Single"},
            {"SP3", "1 Month (1st Class)"},
            {"SP4", "1 Month (Standard)"},
            {"SPG", "Standard plus parking"},
            {"SPN", "VTEC Group Single"},
            {"SPO", "Southeastern Promotion"},
            {"SPP", "SYPTE Zero Fare"},
            {"SPQ", "Southeastern Anytime Promotion"},
            {"SPR", "Super Off-Peak Return"},
            {"SPS", "Super Off-Peak Single"},
            {"SPU", "Business Plus"},
            {"SQF", "Friends Fare"},
            {"SRF", "Seat Reservation Fee"},
            {"SRR", "Super Off-Peak Day Return"},
            {"SS2", "Super Off-Peak Single (Online)"},
            {"SS3", "Smart Super Off-Peak Single"},
            {"SSC", "Standard Shared Cabin"},
            {"SSE", "Fare Card 1 Term"},
            {"SSF", "Fare Card 2 Terms"},
            {"SSG", "Fare Card Annual"},
            {"SSH", "Super Off-Peak Single (Online)"},
            {"SSJ", "Sleeper Seating Single"},
            {"SSK", "Sleeper Seating Single"},
            {"SSL", "Sleeper Seating Single"},
            {"SSM", "Sleeper Seating Single"},
            {"SSN", "Sleeper Seating Single"},
            {"SSR", "Super Off-Peak Return"},
            {"SSS", "Super Off-Peak Single"},
            {"SST", "Stroud Special"},
            {"SSU", "Super Off-Peak Single (Online)"},
            {"STA", "Tour Admit"},
            {"STM", "Network Student"},
            {"STO", "Super Off-Peak Day Travelcard"},
            {"STP", "Super Off-Peak Day Travelcard"},
            {"SUG", "7 Day Upgrade"},
            {"SUS", "Rail Staff Travel Single"},
            {"SV3", "Smart Off-Peak Single"},
            {"SVB", "7 Day Busrl SW"},
            {"SVH", "Off Peak Single (Online)"},
            {"SVR", "Off-Peak Return"},
            {"SVS", "Off-Peak Single"},
            {"SWS", "Super Off-Peak Day Single"},
            {"SWU", "SWT Weekend Upgrade"},
            {"SXD", "St Ives Day Ranger"},
            {"SXF", "St Ives Day Ranger Family"},
            {"SXG", "St Ives Day Ranger Group"},
            {"SZ7", "Temporary Season Replacement"},
            {"SZL", "Scilly Islands Long Stay"},
            {"SZS", "Scilly Islands Short Stay"},
            {"T1R", "Through Off-Peak Day Return Family (1 adult+2 children)"},
            {"T2R", "Through Off-Peak Day Return Family (2 adults + 4 children)"},
            {"TAP", "Travel + Pint"},
            {"TDR", "Through Off-Peak Day Return"},
            {"TER", "Through Off-Peak Day Return Senior"},
            {"TF4", "Flyaway Up to 4"},
            {"TFF", "2 for 1 (1st Class)"},
            {"TFS", "2 for 1 Standard"},
            {"TKR", "Child Flat Fare Return"},
            {"TKS", "Child Flat Fare Single"},
            {"TKT", "Child Flat Fare Travelcard"},
            {"TL1", "Thameslink-Gatwick Express 1st Single Upgrade"},
            {"TL2", "Thameslink-Gatwick Express Single Upgrade"},
            {"TMA", "Travelmaster 12 Months"},
            {"TMM", "Travelmaster 28 Day"},
            {"TMW", "Travelmaster 7 Day"},
            {"TP1", "Advance Single (1st Class)"},
            {"TP2", "Advance Single"},
            {"TP3", "Advance Single (1st Class)"},
            {"TP4", "Advance Single"},
            {"TP6", "Bus Day Rover"},
            {"TP7", "Moors Bus Day Rover"},
            {"TQ1", "Conference Package 1"},
            {"TQ2", "Conference Package"},
            {"TRF", "Travelcard Season (1st Class)"},
            {"TRV", "Travelcard Season"},
            {"TTN", "Take 10 Business"},
            {"TTR", "Take 10 1st"},
            {"TTS", "Take 10 Standard"},
            {"TVS", "Traveller Single"},
            {"TWC", "Travel without charge"},
            {"U20", "VTWC Upgrade 20"},
            {"U25", "VTWC Upgrade 25"},
            {"U30", "VTWC Upgrade 30"},
            {"U35", "VTWC Upgrade 35"},
            {"U40", "VTWC Upgrade 40"},
            {"U45", "VTWC Upgrade 45"},
            {"U50", "VTWC Upgrade 50"},
            {"U70", "VTWC Upgrade 70"},
            {"UBB", "Ullswater Bus &amp; Boat"},
            {"UFA", "Advance Single (1st Class)"},
            {"UFB", "Advance Single (1st Class)"},
            {"UFC", "Advance Single (1st Class)"},
            {"UFD", "Advance Single (1st Class)"},
            {"UFE", "Advance Single (1st Class)"},
            {"UFF", "Advance Single (1st Class)"},
            {"UFG", "Advance Single (1st Class)"},
            {"UFH", "Advance Single (1st Class)"},
            {"UFI", "Advance Single (1st Class)"},
            {"UOP", "Off-Peak Upgrade"},
            {"UPG", "Festival Upgrade"},
            {"USA", "Advance Single"},
            {"USB", "Advance Single"},
            {"USC", "Advance Single"},
            {"USD", "Advance Single"},
            {"USE", "Advance Single"},
            {"USF", "Advance Single"},
            {"USG", "Advance Single"},
            {"USH", "Advance Single"},
            {"USI", "Advance Single"},
            {"USJ", "Advance Single"},
            {"USK", "Advance Single"},
            {"USW", "Advance Single"},
            {"USX", "Advance Single"},
            {"USY", "Advance Single"},
            {"USZ", "Advance Single"},
            {"V1A", "Advance Single (1st Class)"},
            {"V1B", "Advance Single (1st Class)"},
            {"V1C", "Advance Single (1st Class)"},
            {"V1D", "Advance Single (1st Class)"},
            {"V1E", "Advance Single (1st Class)"},
            {"V1F", "Advance Single (1st Class)"},
            {"V1G", "Advance Single (1st Class)"},
            {"V1H", "Advance Single (1st Class)"},
            {"V1I", "Advance Single (1st Class)"},
            {"V1J", "Advance Single (1st Class)"},
            {"V1K", "Advance Single (1st Class)"},
            {"V1L", "Advance Single (1st Class)"},
            {"V1M", "Advance Single (1st Class)"},
            {"V1N", "Advance Single (1st Class)"},
            {"V1O", "Advance Single (1st Class)"},
            {"V1P", "Advance Single (1st Class)"},
            {"V1Q", "Advance Single (1st Class)"},
            {"V1R", "Advance Single (1st Class)"},
            {"V1S", "Advance Single (1st Class)"},
            {"V1T", "Advance Single (1st Class)"},
            {"V1U", "Advance Single (1st Class)"},
            {"V1V", "Advance Single (1st Class)"},
            {"V1W", "Advance Single (1st Class)"},
            {"V1X", "Advance Single (1st Class)"},
            {"V1Y", "Advance Single (1st Class)"},
            {"V1Z", "Advance Single (1st Class)"},
            {"V2A", "Advance Single"},
            {"V2B", "Advance Single"},
            {"V2C", "Advance Single"},
            {"V2D", "Advance Single"},
            {"V2E", "Advance Single"},
            {"V2F", "Advance Single"},
            {"V2G", "Advance Single"},
            {"V2H", "Advance Single"},
            {"V2I", "Advance Single"},
            {"V2J", "Advance Single"},
            {"V2K", "Advance Single"},
            {"V2L", "Advance Single"},
            {"V2M", "Advance Single"},
            {"V2N", "Advance Single"},
            {"V2O", "Advance Single"},
            {"V2P", "Advance Single"},
            {"V2Q", "Advance Single"},
            {"V2R", "Advance Single"},
            {"V2S", "Advance Single"},
            {"V2T", "Advance Single"},
            {"V2U", "Advance Single"},
            {"V2V", "Advance Single"},
            {"V2W", "Advance Single"},
            {"V2X", "Advance Single"},
            {"V2Y", "Advance Single"},
            {"V2Z", "Advance Single"},
            {"VA1", "Advance Single"},
            {"VA2", "Advance Single"},
            {"VA3", "Advance Single"},
            {"VA4", "Advance Single"},
            {"VA5", "Advance Single"},
            {"VA6", "Advance Single (1st Class)"},
            {"VAL", "Limo Anytime"},
            {"VAS", "Advance Single"},
            {"VBR", "Virgin Business Package"},
            {"VBS", "Advance Single"},
            {"VCA", "VTWC 2 Group A"},
            {"VCB", "VTWC 2 Group B"},
            {"VCC", "VTWC 2 Group C"},
            {"VCD", "VTWC 2 Group D"},
            {"VCE", "VTWC 2 Group E"},
            {"VCF", "VTWC 2 Group F"},
            {"VCG", "VTWC 2 Group G"},
            {"VCH", "VTWC 2 Group H"},
            {"VCI", "VTWC 2 Group I"},
            {"VCJ", "VTWC 2 Group J"},
            {"VCK", "VTWC 2 Group K"},
            {"VCS", "Advance Single"},
            {"VDS", "Advance Single"},
            {"VER", "Valley Evening Return"},
            {"VES", "Advance Single"},
            {"VFA", "VTWC 1 Group A"},
            {"VFB", "VTWC 1 Group B"},
            {"VFC", "VTWC 1 Group C"},
            {"VFD", "VTWC 1 Group D"},
            {"VFE", "VTWC 1 Group E"},
            {"VFG", "VTWC 1 Group F"},
            {"VFP", "Red Hot Single"},
            {"VIF", "WC ITX 1st High"},
            {"VIS", "WC ITX Standard High"},
            {"VJF", "WC ITX 1st Medium"},
            {"VJS", "WC ITX Standard Medium"},
            {"VKF", "WC ITX Low 1st Class"},
            {"VKS", "WC ITX Low (Std)"},
            {"VP1", "Virgin Partner (1st Class)"},
            {"VP2", "Virgin Partner (Standard Class)"},
            {"VSG", "VTWC School Group"},
            {"VSR", "VT2 Group Travel DR"},
            {"VT1", "VTWC GBP1 Shop"},
            {"VT2", "VTWC GBP2 Shop"},
            {"VT3", "VTWC GBP3 Shop"},
            {"VT5", "VTWC GBP5 Shop"},
            {"VTR", "VT2 Group Trabel CR"},
            {"VUO", "VT2 Group Travel BS"},
            {"VUR", "VT2 Group Travel BR"},
            {"VVF", "Advance Family Ticket Return"},
            {"VVR", "VT2 Group Travel AR"},
            {"VW1", "VTWC Promo 1"},
            {"VWD", "VTWC Wday Upgrade"},
            {"VWU", "Virgin Weekend Upgrade"},
            {"VYR", "VT1 Group Travel BR"},
            {"VZP", "Sale Standard"},
            {"VZR", "VT1 Group Travel AR"},
            {"W1A", "Advance Single (1st Class)"},
            {"W1C", "Advance Single (1st Class)"},
            {"W1E", "Advance Single (1st Class)"},
            {"W1G", "Advance Single (1st Class)"},
            {"W1H", "Advance Single (1st Class)"},
            {"W1J", "Advance Single (1st Class)"},
            {"W1L", "Advance Single (1st Class)"},
            {"W1N", "Advance Single (1st Class)"},
            {"W1O", "Advance Single (1st Class)"},
            {"W1P", "Advance Single (1st Class)"},
            {"W1Q", "Advance Single (1st Class)"},
            {"W1R", "Advance Single (1st Class)"},
            {"W1S", "Advance Single (1st Class)"},
            {"W1T", "Advance Single (1st Class)"},
            {"W1U", "Advance Single (1st Class)"},
            {"W1V", "Advance Single (1st Class)"},
            {"W1W", "Advance Single (1st Class)"},
            {"W1X", "Advance Single (1st Class)"},
            {"W1Y", "Advance Single (1st Class)"},
            {"W1Z", "Advance Promo Single (1st Class)"},
            {"W2A", "Advance Single"},
            {"W2B", "Advance Single"},
            {"W2C", "Advance Single"},
            {"W2D", "Advance Single"},
            {"W2E", "Advance Single"},
            {"W2F", "Advance Single"},
            {"W2G", "Advance Single"},
            {"W2H", "Advance Single"},
            {"W2I", "Advance Single"},
            {"W2J", "Advance Single"},
            {"W2K", "Advance Single"},
            {"W2L", "Advance Single"},
            {"W2M", "Advance Single"},
            {"W2N", "Advance Single"},
            {"W2O", "Advance Single"},
            {"W2P", "Advance Single"},
            {"W2Q", "Advance Single"},
            {"W2R", "Advance Single"},
            {"W2S", "Advance Single"},
            {"W2T", "Advance Single"},
            {"W2U", "Advance Single"},
            {"W2V", "Advance Single"},
            {"W2W", "Advance Single"},
            {"W2X", "Advance Single"},
            {"W2Y", "Advance Single"},
            {"W2Z", "Advance Promo Single"},
            {"W6A", "WYCA Annual Zone 6"},
            {"W6M", "WYCA Month Zone 6"},
            {"W6Q", "WYCA Quarterly Zone 6"},
            {"W6W", "WYCA Week Zone 6"},
            {"W7A", "WYCA Annual Zone 7"},
            {"W7M", "WYCA Month Zone 7"},
            {"W7Q", "WYCA Quarterly Zone 7"},
            {"W7W", "WYCA Week Zone 7"},
            {"WA1", "Adult Day Friday"},
            {"WA2", "Adult Day Saturday"},
            {"WA3", "Adult Day Sunday"},
            {"WA4", "Adult Weekend"},
            {"WA5", "Adult VIP Weekend"},
            {"WA6", "Adult VIP Friday"},
            {"WA7", "Adult VIP Saturday"},
            {"WAD", "WSR Away Day"},
            {"WAP", "West Somerset Railway Explorer"},
            {"WAS", "Advance Single"},
            {"WB1", "Student Day Friday"},
            {"WB2", "Student Day Saturday"},
            {"WB3", "Student Day Sunday"},
            {"WB4", "Student Weekend"},
            {"WB5", "Student VIP Weekend"},
            {"WBS", "Advance Single"},
            {"WC1", "Virgin Trains West Coast Corporate Return (1st Class)"},
            {"WC2", "Virgin Trains Business Standard Return "},
            {"WC3", "Virgin Trains West Coast Corporate Single"},
            {"WC4", "VT Business Return A"},
            {"WC5", "VT Corporate+ A"},
            {"WCC", "VT Corporate +"},
            {"WCS", "Advance Single"},
            {"WDS", "Advance Single"},
            {"WDT", "Super Off-Peak Day Travelcard"},
            {"WES", "Advance Single"},
            {"WET", "Weekend 1st Upgrade"},
            {"WFS", "Advance Single"},
            {"WFU", "EMT Weekend 1st"},
            {"WGS", "Advance Single"},
            {"WHS", "Advance Single"},
            {"WJS", "Advance Single"},
            {"WK1", "Weekender Return (1st Class)"},
            {"WK2", "Southeastern Weekender"},
            {"WK3", "Southeastern Weekender Return"},
            {"WKC", "Weekend Travelcard"},
            {"WKS", "Advance Single"},
            {"WKU", "Weekend 1st Class Upgrade"},
            {"WLS", "Advance Single"},
            {"WMT", "Business Zone Package"},
            {"WMX", "Business Zone Return"},
            {"WOD", "Web Off-Peak Day Return"},
            {"WOR", "Web Off-Peak Return"},
            {"WOS", "Web Off-Peak Day Single"},
            {"WPS", "Advance Single"},
            {"WRE", "Super Off-Peak Day Travelcard"},
            {"WRO", "Web Weekender"},
            {"WSO", "Web Super Off-Peak Day Return"},
            {"WSP", "London Wasps Rugby FC"},
            {"WSS", "Web Super Off-Peak Single"},
            {"WTC", "Super Off-Peak Day Travelcard"},
            {"WUG", "Grand Central Weekend Upgrade"},
            {"WUR", "Weekend First Upgrade Return"},
            {"WUS", "Weekend First Upgrade Single"},
            {"WW1", "Arriva Trains Wales Weekend First"},
            {"X1C", "CrossCountry Complementary 1st Class"},
            {"X2C", "CrossCountry Complementary Standard"},
            {"XAF", "Advance Single (1st Class)"},
            {"XBF", "Advance Single (1st Class)"},
            {"XBR", "Executive Ticket GWR Packages"},
            {"XC1", "Business Package Return (Standard Class)"},
            {"XC3", "CrossCountry Small Group 3"},
            {"XC4", "CrossCountry Small Group 4"},
            {"XC5", "CrossCountry Small Group 5"},
            {"XC6", "CrossCountry Small Group 6"},
            {"XC7", "CrossCountry Small Group 7"},
            {"XC8", "CrossCountry Small Group 8"},
            {"XC9", "CrossCountry Small Group 9"},
            {"XCF", "Advance Single (1st Class)"},
            {"XCT", "CrossCountry Explorer"},
            {"XCU", "IXC Weekend Upgrade"},
            {"XDF", "Advance Single (1st Class)"},
            {"XDR", "Promo Day Return"},
            {"XEF", "Advance Single (1st Class)"},
            {"XFF", "Advance Single (1st Class)"},
            {"XGF", "Advance Single (1st Class)"},
            {"XLF", "VTEC Rewards 1st Class"},
            {"XP1", "First Park and Go"},
            {"XP2", "First Park and Go"},
            {"XS1", "Scottish Executive Package - Return"},
            {"XS2", "Scottish Executive Package - Return"},
            {"XS3", "VTEC Corporate Standard Single"},
            {"XS5", "VTEC Corporate Standard Single"},
            {"XS6", "Scottish Executive Package - Single"},
            {"XS8", "West Yorkshire Executive Package"},
            {"ZDS", "Anytime Day Single"},
            {"ZN4", "Strathclyde PTE Zone 4 Week"},
            {"ZNA", "Strathclyde PTE Annual"},
            {"ZNW", "Strathclyde PTE Zone 1 Week"},
            {"ZNX", "Strathclyde PTE 10 Weeks"},
            {"ZO3", "Magstripe Conversion (Std Class)"},
            {"ZO4", "Magstripe Conversion (1st Class)"},
            {"ZOP", "Chiltern Off-Peak 1st"},
            {"ZOR", "Anytime Return"},
            {"ZPO", "Port Tax"},
            {"ZZV", "Not for travel"},
            {"ZZW", "Not for travel"},
            {"ZZX", "Not for travel"},
            {"ZZY", "Not valid for travel"},
            {"ZZZ", "Not valid for travel"}
        };
        public static string GetTicketTypeName(string code)
        {
            codeToName.TryGetValue(code, out var name);
            return name;
        }
    }
}
